[package]
name = "neomind-extension-sdk"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "SDK for building NeoMind dynamic plugins"

[lib]
name = "neomind_extension_sdk"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
neomind-core = { path = "../neomind-core" }
async-trait = { workspace = true }
chrono = { workspace = true }
semver = { workspace = true }
rand = "0.8"

[features]
default = []
test-utils = []
